spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gestion_de_stock?serverTimezone=UTC
    username: root
    password:
  jpa:
    show-sql: false
    database: MYSQL
    properties:
      hibernate:
        ejb:
          interceptor: com.eljayi.gestiondestock.interceptor.Interceptor
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
server:
  port: 8081

flickr:
  apiKey: 9f7d04a465998080a166a71df1121a6a
  apiSecret: 4aea2982cc84d512
  appKey: 72157720842717015-2191041c179c3295
  appSecret: d1d10a19096ea935


