spring:
  datasource:
    url: jdbc:mysql://localhost:3308/gestiondestock?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password:
  jpa:
    show-sql: false
    database: MYSQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
#  datasource:
#    url: jdbc:mysql://localhost:3308/gestiondest?createDatabaseIfNotExist=true&userSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#    username: root
#    password:
#    driver-classname: com.mysql.cj.jdbc.Driver
###Specify DBMS
#  jpa:
#    database: MYSQL
#    show-sql: false
## Hibernate DDL AUTO (create, create-drop, update)
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySAL5Dialect
server:
  port: 8081


